x-app: &app
  build: .
  volumes:
    - ./log/erlang-history:/log/erlang-history
    - ./log/shell-history:/log/shell-history
  environment:
    ERL_AFLAGS: -kernel shell_history enabled -kernel shell_history_path '"/log/erlang-history"'
    HISTSIZE: 10000
    HISTFILE: /log/shell_history

services:
  gen_game:
    <<: *app
    command: /bin/sh -c "mix deps.get && mix setup && elixir --sname gen_game --cookie g3ng4m3 -S mix phx.server --no-halt"
    container_name: gen_game
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/gen_game_dev
    ports:
      - 4000:4000

  postgres:
    image: postgres:16-alpine
    healthcheck:
      test: "pg_isready -U postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  db2:
    image: icr.io/db2_community/db2
    container_name: db2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1 # Db2 instance name
      - DB2INST1_PASSWORD=password # Set your desired password here
      - DBNAME=db2vspg # Database name
    volumes:
      - db2:/database
    ports:
      - 50000:50000

volumes:
  postgres:
  db2:
